#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Phase 6: Application Deployment
# ═══════════════════════════════════════════════════════════════
# Deploys the application to EC2 via SSH. Creates a GitHub deploy
# key, clones the repo, configures .env, installs deps, starts PM2.
# ═══════════════════════════════════════════════════════════════
source "$(dirname "$0")/config.sh"
banner "Phase 6: Application Deployment"

EIP_PUBLIC=$(require_state EIP_PUBLIC)
KEY_PATH=$(require_state KEY_PATH)

SSH="ssh -i ${KEY_PATH} -o StrictHostKeyChecking=no ec2-user@${EIP_PUBLIC}"
SCP="scp -i ${KEY_PATH} -o StrictHostKeyChecking=no"

# ── Verify SSH connectivity ──────────────────────────────────
step "Testing SSH connectivity"

if ! $SSH "echo ok" 2>/dev/null; then
  err "Cannot SSH to ec2-user@${EIP_PUBLIC}"
  echo "  Check: security group allows port 22 from your IP"
  echo "  Check: key file exists at ${KEY_PATH}"
  exit 1
fi
info "SSH connected to $EIP_PUBLIC"

# ── Validate config ──────────────────────────────────────────
step "Validating deployment configuration"

if [ -z "$GITHUB_REPO" ]; then
  err "GITHUB_REPO is not set in config.sh"
  echo "  Set it to your repository URL, e.g.:"
  echo "  GITHUB_REPO=\"git@github.com:youruser/linkedin-agent.git\""
  exit 1
fi
info "Target repo: $GITHUB_REPO"

# ── GitHub Deploy Key ─────────────────────────────────────────
step "Generating GitHub deploy key on EC2"

$SSH << 'DEPLOYKEY'
if [ ! -f ~/.ssh/github_deploy_key ]; then
  ssh-keygen -t ed25519 -f ~/.ssh/github_deploy_key -N "" -C "linkedin-agent-deploy" -q
  cat > ~/.ssh/config << 'SSHCFG'
Host github.com
  IdentityFile ~/.ssh/github_deploy_key
  StrictHostKeyChecking no
SSHCFG
  chmod 600 ~/.ssh/config
fi
DEPLOYKEY

DEPLOY_PUB=$($SSH "cat ~/.ssh/github_deploy_key.pub")

banner "ACTION REQUIRED: Add Deploy Key to GitHub"
echo "  Go to your GitHub repository → Settings → Deploy keys → Add deploy key"
echo ""
echo "  Title: linkedin-agent-ec2-deploy"
echo "  Key:"
echo "  $DEPLOY_PUB"
echo ""
echo "  ☐  Allow write access: UNCHECKED (read-only is sufficient)"
echo ""
read -p "  Press Enter after adding the deploy key to GitHub... " _

# ── Verify GitHub access ─────────────────────────────────────
step "Testing GitHub access from EC2"

GH_TEST=$($SSH "ssh -T git@github.com 2>&1" || true)
if echo "$GH_TEST" | grep -qi "successfully authenticated\|You've successfully"; then
  info "GitHub authentication successful"
else
  warn "GitHub response: $GH_TEST"
  echo "  If this says 'Permission denied', verify the deploy key was added."
  read -p "  Press Enter to continue anyway, or Ctrl+C to abort... " _
fi

# ── Clone Repository ──────────────────────────────────────────
step "Cloning repository"

$SSH << CLONECMD
cd /home/ec2-user
if [ -d linkedin-agent ]; then
  cd linkedin-agent
  git fetch origin
  git reset --hard origin/${GITHUB_BRANCH}
  echo "Updated existing clone"
else
  git clone --branch ${GITHUB_BRANCH} ${GITHUB_REPO} linkedin-agent
  echo "Fresh clone complete"
fi
CLONECMD

info "Repository cloned to /home/ec2-user/linkedin-agent"

# ── Create .env ───────────────────────────────────────────────
step "Configuring .env for production"

echo ""
echo "  The .env file needs your secrets. I'll prompt for each one."
echo "  Values are NOT echoed to the terminal."
echo ""

read -sp "  ANTHROPIC_API_KEY_ENCRYPTED: " ANTHROPIC_ENC; echo ""
read -sp "  ENCRYPTION_SECRET: " ENC_SECRET; echo ""
read -sp "  ENCRYPTION_SALT: " ENC_SALT; echo ""
read -sp "  AUTH0_CLIENT_SECRET: " AUTH0_SECRET; echo ""
read -sp "  SESSION_SECRET (64+ hex chars): " SESS_SECRET; echo ""
read -p  "  AUTH0_DOMAIN (e.g., dev-xyz.us.auth0.com): " AUTH0_DOMAIN
read -p  "  AUTH0_CLIENT_ID: " AUTH0_CLIENT_ID

cat << ENVEOF | $SSH "cat > /home/ec2-user/linkedin-agent/.env"
# ═══════════════════════════════════════════════════════════════
# LinkedIn AI Agent — Production Configuration
# Generated by deployment script on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ═══════════════════════════════════════════════════════════════

# ── Application ───────────────────────────────────────────────
NODE_ENV=production
APP_BASE_URL=https://${FQDN}
DASHBOARD_PORT=${APP_PORT}
AGENT_MODE=manual

# ── CORS / Origins ────────────────────────────────────────────
ALLOWED_ORIGINS=https://${FQDN}

# ── Encryption (API key at rest) ──────────────────────────────
ANTHROPIC_API_KEY_ENCRYPTED=${ANTHROPIC_ENC}
ENCRYPTION_SECRET=${ENC_SECRET}
ENCRYPTION_SALT=${ENC_SALT}

# ── Auth0 ─────────────────────────────────────────────────────
AUTH0_DOMAIN=${AUTH0_DOMAIN}
AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
AUTH0_CLIENT_SECRET=${AUTH0_SECRET}
AUTH0_AUDIENCE=https://linkedin-agent-api
AUTH0_REDIRECT_URI=https://${FQDN}/auth/callback
AUTH0_LOGOUT_URI=https://${FQDN}
AUTH0_SCOPES=openid profile email

# ── Session ───────────────────────────────────────────────────
SESSION_SECRET=${SESS_SECRET}
ENVEOF

info ".env created on EC2"

# ── Install Dependencies ──────────────────────────────────────
step "Installing npm dependencies"

$SSH << 'NPMINST'
cd /home/ec2-user/linkedin-agent
npm ci --omit=dev 2>&1 | tail -3
echo "Dependencies installed"
NPMINST

info "npm ci complete"

# ── Build ─────────────────────────────────────────────────────
step "Running build step"

$SSH << 'BUILD'
cd /home/ec2-user/linkedin-agent
npm run build_js 2>&1
echo "Build complete"
BUILD

info "build_js complete"

# ── Trust Proxy ───────────────────────────────────────────────
step "Verifying trust proxy setting"

HAS_TRUST=$($SSH "grep -c 'trust proxy' /home/ec2-user/linkedin-agent/src/index.js" 2>/dev/null || echo "0")
if [ "$HAS_TRUST" = "0" ]; then
  warn "trust proxy not found in src/index.js"
  echo "  Add this line after 'const app = express();':"
  echo "    app.set('trust proxy', true);"
  echo "  Then rebuild: npm run build_js"
else
  info "trust proxy is configured"
fi

# ── Start with PM2 ───────────────────────────────────────────
step "Starting application with PM2"

$SSH << 'PM2START'
cd /home/ec2-user/linkedin-agent
pm2 delete linkedin-agent 2>/dev/null || true
pm2 start src/index.js \
  --name linkedin-agent \
  --max-memory-restart 512M \
  --log-date-format "YYYY-MM-DD HH:mm:ss" \
  --merge-logs
pm2 save
echo ""
pm2 status
PM2START

info "Application started via PM2"

# ── Summary ───────────────────────────────────────────────────
banner "Phase 6 Complete"
echo "  Application: Running on ${EIP_PUBLIC}:${APP_PORT}"
echo "  PM2 status:  ssh -i ${KEY_PATH} ec2-user@${EIP_PUBLIC} 'pm2 status'"
echo "  PM2 logs:    ssh -i ${KEY_PATH} ec2-user@${EIP_PUBLIC} 'pm2 logs'"
echo ""
echo "  Next: bash 07-verify.sh"
